version: 2
jobs:
  build:
    working_directory: ~/react-cordova-appium-ci
    docker:
      - image: node:7.9.0
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: Build web
          command: npm run build
      - run:
          name: Install E2E script dependencies
          command: |
            apt update
            apt install -y rsync
      - run:
          name: E2E test
          command: |
            rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${SSH_PORT}" /home/ubuntu/react-cordova-appium-ci/build/ ${REMOTE_SERVER}:${REMOTE_PROJECT_DIR}/cordova/www
            ssh -p ${SSH_PORT} ${REMOTE_SERVER} 'cd ${REMOTE_PROJECT_DIR}/cordova && cordova build android --debug && npm run test'